### ISSUE TITLE
People.Get method is taking more time to respond

### ISSUE THREAD

**Issue by RakeshLaveti** [code4me/4me-sdk-csharp#57]
Hi @klaasvandeweerdt ,

We observed that 4MEUser plugin is continuously running for multiple users and People.Get method is not responding which leads to multiple 4MeUser instances are struck.

After restarting the deployment server, it gets fixed automatically.

Is there any possibility to set the execution time for those methods? (or) any better way to call those methods with out queueing multiple instances?

Thanks,
Rakesh.

**Comment by klaasvandeweerdt** [comment]
Hi @RakeshLaveti,

There is a known issue in all versions prior to 2.0.3.2 with the sleep between API requests functionality. Make sure to update to at least 2.0.3.2. An upgrade to 2.0.4 will require some additional attention when using custom fields, as custom fields is now an ```<string,object>``` collection instead of ```<string,string>```. More details about the existing versions are available [here](https://github.com/code4me/4me-sdk-csharp/releases).

Klaas
