### ISSUE TITLE
Question - Get Requested_by and Requested_For on a RFC

### ISSUE THREAD

**Issue by RobertOsterberg** [code4me/4me-sdk-csharp#59]
Hi Klass
can you explain why all of the properties are not returned when getting a RFC for example. I am looking in particular for the requested_by and the Requested_for. are the not a part of the RFC not even the ID is returned.

Have a great day.

**Comment by klaasvandeweerdt** [comment]
Hi Robert,

Every REST API endpoint returns a default set of fields. You can find the default fields in the [documentation](https://developer.4me.com/v1/requests/#collection-fields). For requests this is ```id``` ```source``` ```subject``` ```category``` ```impact``` ```status``` ```next_target_at``` ```completed_at``` ```team``` ```member``` ```grouped_into``` ```service_instance``` ```created_at``` ```updated_at```. This is by design, returning all fields impacts performance, and most of the time that data is useless. You should always try to specify which data you need to optimize performance, especially with large datasets. The data that you need depends on your scenario. I can think of as many scenarios where I would need ```requested_for``` and ```requested_by```, as I can think of scenarios where I don't need that data.

When querying for data try to use as many filters as possible this reduces the number of data.
Always specify the fields that you need. An example:
 ```csharp
client.requests.Get("ID", "RequestedBy", "Subject")
```
I hope this helps.

**Comment by RobertOsterberg** [comment]
thanks for your guidence Klaas
i got it working by doing this

var requestDetails = client.Requests.Get(request.ID);
and got all standard fields returned from the request.

I had some problems with this filtercondition.Equality
new Filter("Team", FilterCondition.Equality, "The TeamName"), 

but it worked fine when i changed to the Id instead
new Filter("TeamID", FilterCondition.Equality, 14037), 

have a nice day

**Comment by klaasvandeweerdt** [comment]
Hi Robert,

Good to see that you got it working.

When you use ```.Get(long id)```, like you example ```client.Requests.Get(request.ID);```, you will always get all fields.
If you use ```client.Requests.Get(new Filter("id", FilterCondition.Equals, request.ID));``` you get the defaults fields because it is filtered result.

For the filtering, team is not a name but a set of fields, a direct filter on team will not work. This applies to all data objects.
