### ISSUE TITLE
Filtering on Completion Reason

### ISSUE THREAD

**Issue by RobertOsterberg** [code4me/4me-sdk-csharp#65]
Hi Klaas
i was fiddling around with the filtering and tried filtering on the Completion reason.
In 4me on the request you can set a filter on Completion reason.

![image](https://user-images.githubusercontent.com/18688250/213368197-a7b3e457-d087-4d16-8445-052bb95a17d4.png)

And the filter exist in the code as
new Filter("CompletionReason", FilterCondition.Equality, RequestCompletionReason.Solved),

But the filter throws an exception
{"Filtering not allowed on fields: completion_reason."}

exception from our logs

2023-01-19 09:57:52.291 +00:00 [ERR] Error converting value "rejected" to type 'System.Nullable`1[Sdk4me.RequestCompletionReason]'. Path 'completion_reason', line 1, position 370.    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

Any idea to why?

**Comment by klaasvandeweerdt** [comment]
Hi Robert,

These are 2 separate issues.
The second one is causing an error because the `RequestCompletionReason` enumerator does not contain the `rejected` value. This is related to your previous question #64. I added the missing enumerator values and I will push and publish the updates over the weekend. This will be resolved by Monday.
In the new [GaphQL SDK](https://github.com/code4me/4me-sdk-graphql-dotnet) I added a way to specify how serialization should work in case it encounters an unknown enumerator value. When enable it does not throw an exception but uses the default value, which is either `null` for a nullable enum value or `0` for a non-nullable enum value. I can add similar functionality to the REST API SDK. Would that help in the future? This means if there is a new `RequestCompletionReason` value that is not available in the SDK it will return `null`.

For the first one `{"Filtering not allowed on fields: completion_reason."}` this is a limitation of the API. The SDK allows you to enter any field and value, but you can only use the fields as [documented](https://developer.4me.com/v1/requests/#filtering). I suggest you raise a request with 4me as this is not a change in the SDK but in the API.

**Comment by klaasvandeweerdt** [comment]
Hi @RobertOsterberg 
The Git Release and NuGet 2.0.8 are available, it contains the missing `RequestCompletionReason` enum values.

**Comment by RobertOsterberg** [comment]
HI Klaas
So i updated the service and tried my CompletionReason filter again but got the same exception
{"Filtering not allowed on fields: completion_reason."}

i used
new FilterCollection()
                    {
                    new Filter("Status", FilterCondition.Equality, RequestStatus.Completed),
                    new Filter("CompletionReason", FilterCondition.Equality, RequestCompletionReason.Solved),
                    new Filter("TeamID", FilterCondition.Equality, int.Parse(System.Configuration.ConfigurationManager.AppSettings[$"{GetEnvironment()}AmeliaTeam"])), //Amelia Team
                    new Filter("Category", FilterCondition.Equality, RequestCategory.RFC),
                    new Filter("Member", FilterCondition.Equality, int.Parse(System.Configuration.ConfigurationManager.AppSettings[$"{GetEnvironment()}ChangeMember"])), //change member
                    new Filter("ServiceInstance", FilterCondition.Equality,int.Parse(System.Configuration.ConfigurationManager.AppSettings[$"{GetEnvironment()}ServiceInstance"])) //Service Instance 
                    }
as filter works fine without the Completion Reason

and then i saw that the Request it self reurns null in CompletionReason when i don`t use it as filter
![image](https://user-images.githubusercontent.com/18688250/213994820-fddb3e63-46f1-4a68-a257-2b63c5ebc58d.png)

this picture is from using this filter
`   new FilterCollection()
                    {
                    new Filter("Status", FilterCondition.Equality, RequestStatus.Completed),
                    new Filter("TeamID", FilterCondition.Equality, int.Parse(System.Configuration.ConfigurationManager.AppSettings[$"{GetEnvironment()}AmeliaTeam"])), //Amelia Team
                    new Filter("Category", FilterCondition.Equality, RequestCategory.RFC),
                    new Filter("Member", FilterCondition.Equality, int.Parse(System.Configuration.ConfigurationManager.AppSettings[$"{GetEnvironment()}ChangeMember"])), //change member
                    new Filter("ServiceInstance", FilterCondition.Equality,int.Parse(System.Configuration.ConfigurationManager.AppSettings[$"{GetEnvironment()}ServiceInstance"])) //Service Instance 
                    }
                );`
Any thoughts?

**Comment by klaasvandeweerdt** [comment]
Hi Robert,

The "Filtering not allowed on fields: completion_reason." error is a limitation of the API, not the SDK. The SDK allows you to enter any field and value, but you can only use the fields as [documented](https://developer.4me.com/v1/requests/#filtering). I would suggest you raise a request with 4me because this is not a change in the SDK but in the API.

The value of the completion reason is null because the API does not return it by default. The [documentation](https://developer.4me.com/v1/requests/#collection-fields) also contains a list of default fields or `collection fields`. Those are the fields returned by default, if you need other fields you have to specify them.

This example will only retrieves the `ServiceInstance`, `CompletionReason`, and `Status` values, all other fields will be `null`.
```csharp
Sdk4meClient client = new Sdk4meClient(tokens, "sdk-csharp", EnvironmentType.Quality, 100, 10);
var result = client.Requests.Get(new FilterCollection()
{
     { "Status", FilterCondition.Equality, RequestStatus.Completed },
     { "TeamID", FilterCondition.Equality, 1234 }
}, "ID", "ServiceInstance", "CompletionReason", "Status");
```

**Comment by RobertOsterberg** [comment]
HI
Naice it worked great!! thank you.
the only issue was to use the 
{ CreatedAt", FilterCondition.GreaterThanOrEqualToAndLessThanOrEqualTo, yesterday, tomorrow } filter in the collection
it complained about DateTime to short.

 
Another question for you, I am a bit worried that the limit for requests on the API is going to be an issue and that the token contains the info and yes it does but it doesn`t seem to count requests and change when a request is made
it stays the same every time
![image](https://user-images.githubusercontent.com/18688250/214227099-ccb03da6-9b4b-48c2-81c0-8eda429e450f.png)

or am i missing something?
And where is the actual request to the API being made?
Is number of requests being returned, every time you call your get requests or when the client is initialized.

Thanks again for your time

Have a great day

**Comment by klaasvandeweerdt** [comment]
It looks like the filters do not have a method to add two `datetime` values.
You can use this instead.
```csharp
List<Request> requests = client.Requests.Get(new FilterCollection()
{
    new Filter("Status", FilterCondition.Negation, RequestStatus.Completed),
    new Filter("CreatedAt", FilterCondition.GreaterThanOrEqualToAndLessThanOrEqualTo, DateTime.Now.AddDays(-1), DateTime.Now)
}, "ID", "CustomFields", "Status");
```

The token information is only updated once a request is made. To keep track of the token you cannot re-initialize it every time.
Every time you create a new instance of the `AuthenticationToken` via the app settings it will set it by default to 3600. It only updates it after a get, insert, or update. You cannot test upfront as it needs an API call to get that information.
