### ISSUE TITLE
Very outdated code

### ISSUE THREAD

**Issue by MmirzaExd** [code4me/4me-sdk-csharp#73]
I just cloned the repo and tried to build it. Unfortunately the code is using very outdated libraries net452 and net5 both are not supported anymore. 
This repo needs to be updated in order to be useful.

**Comment by klaasvandeweerdt** [comment]
@MmirzaExd,
I updated the target frameworks for the solution. I removed netcoreapp3.1 and net5.0, I also and updated net452 to net462.
For new development, I do recommend using the [.NET SDK for 4me GraphQL](https://github.com/code4me/4me-sdk-graphql-dotnet), or the [GraphQL API](https://developer.4me.com/graphql/) instead of the rest API if you don't use the NuGet packages.
